version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.19.0

    #working_directory: /go/src/github.com/arcology-network/3rd-party
    steps:
      - checkout
      - run: go env -w GOPRIVATE=github.com/arcology-network
      #- run: go mod tidy
      - run: go build ./...