version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/arcology/3rd-party
    steps:
      - checkout
      - run: go env -w GOPRIVATE=github.com/arcology
      - run: go build ./...